version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip3 install awscli 

  build:
    commands:
      - cd runbooks
      - aws sm create-document --content file://
